local opt = vim.opt

-- Leader keys (must be set before plugins).
vim.g.mapleader = " "
vim.g.maplocalleader = "\\"

-- Display
opt.number = true
opt.relativenumber = false
opt.signcolumn = "yes"
opt.cursorline = true
opt.scrolloff = 4
opt.sidescrolloff = 8
opt.wrap = false
opt.termguicolors = true
opt.showmode = false
opt.laststatus = 3
opt.cmdheight = 1

-- Editing
opt.expandtab = true
opt.shiftwidth = 2
opt.tabstop = 2
opt.softtabstop = 2
opt.smartindent = true
opt.breakindent = true
opt.undofile = true
opt.swapfile = false

-- Search
opt.ignorecase = true
opt.smartcase = true
opt.inccommand = "split"

-- Splits
opt.splitright = true
opt.splitbelow = true

-- Diff (Diffview / :diffthis / mergetool).
-- `linematch` is the key to VS Code-style diffs: it runs a second-stage
-- alignment inside each changed block so unchanged lines line up across
-- panes and only the lines that actually differ get highlighted (with
-- word-level DiffText inside them), instead of painting the whole region
-- solid red/green. `algorithm:histogram` produces tighter, more intuitive
-- hunks than the default Myers diff. `iwhiteeol` ignores trailing-whitespace
-- changes (matching VS Code's default `ignoreTrimWhitespace`), so pure
-- end-of-line whitespace edits don't get flagged while real indentation
-- changes still show.
--
-- `linematch:N` only runs its line-aligning second stage when a hunk has at
-- most N lines total; bigger hunks fall back to painting the whole block
-- solid red/green. Merge/revert conflicts routinely produce hunks well over
-- 100 lines, so the value is set high (VS Code aligns these regardless of
-- size). The cost is O(n²) work per hunk, but it's imperceptible at this size.
opt.diffopt = {
  "internal",
  "filler",
  "closeoff",
  "algorithm:histogram",
  "indent-heuristic",
  "iwhiteeol",
  "linematch:400",
}

-- Mouse
opt.mouse = "a"

-- ctags: search upward from cwd for a `.tags` file (project convention, e.g.
-- one generated by `ctags -f .tags ...`), falling back to the classic `tags`
-- name. Powers <C-]>/g] built-ins and the Telescope tags pickers below.
opt.tags = ".tags;,tags;"

-- Filetype mappings
vim.filetype.add({
	extension = {
		hpp = "cpp",
		hxx = "cpp",
		hh = "cpp",
		ipp = "cpp",
	},
})

-- Clipboard: use system clipboard, with OSC 52 for SSH sessions.
opt.clipboard = "unnamedplus"

local osc52 = require("vim.ui.clipboard.osc52")
vim.g.clipboard = {
	name = "OSC 52",
	copy = {
		["+"] = osc52.copy("+"),
		["*"] = osc52.copy("*"),
	},
	paste = {
		["+"] = function() end,
		["*"] = function() end,
	},
}

-- Sensible diagnostic display.
vim.diagnostic.config({
	virtual_text = { prefix = "●" },
	severity_sort = true,
	float = { border = "rounded", source = true },
})
