-- Eagerly load every plugin module. Order matters for colorscheme.
require("plugins.colorscheme")
require("plugins.bufferline")
require("plugins.ui")
require("plugins.noice")
require("plugins.colorizer")
require("plugins.editing")
require("plugins.treesitter")
require("plugins.telescope")
require("plugins.git")
require("config.lsp")
require("plugins.cmp")
require("plugins.format")
require("plugins.explorer")
require("plugins.markdown")
